# 파이썬 입문 (*p.425~*)

*내 기준 정리 필요한 부분들만 선별 정리하였음.*

<br>

list indexing할 때 주의사항:

list[n1:n2]에서 n2는 `n2-1`**까지**임.




In [2]:
list = [1, 2, 3, 4, 5]
print(str(list[0:3]) + "은 리스트의 세 번째가 아닌 두 번째까지 인덱싱된다.")

[1, 2, 3]은 리스트의 세 번째가 아닌 두 번째까지 인덱싱된다.


맨앞부터 또는 맨뒤까지 참조할 경우, 각각 앞, 뒤를 생략할 수 있다.

In [5]:
list = [1, 2, 3, 4, 5]
print(list[:2])
print(list[-3:])

[1, 2]
[3, 4, 5]


튜플

- 튜플은 수정이 불가하다.
- `=`의 우변과 좌변이 서로 요소 수가 동등한 튜플이라면 **여러 개의 변수에 동시 대입이 가능**

In [7]:
z = 1, 2
a, b = z
print(a)
print(b)

1
2


dict 와 for loop을 통해 다음의 loop 처리를 할 수 있다:

In [1]:
dict = {'a':1, 'b':2, 'c':3}

for key, value in dict.items():
    print(key, ':', value)

a : 1
b : 2
c : 3


# Numpy 입문 (*p.448~*)

**Numpy**: 표 형식의 데이터 간 계산을 쉽게 할 수 있게 하는 툴 모음

In [2]:
import numpy as np
np.set_printoptions(suppress=True, precision=5) # 소수점 다섯 번째 자리까지만 출력

## 벡터

In [7]:
n1 = np.array([1, 2, 3, 4, 5, 6, 7])

In [10]:
print(n1)
print(n1.shape)
print(len(n1))

[1 2 3 4 5 6 7]
(7,)
7


array 함수의 인수(parameter)로 리스트를 넣으면 벡터가 만들어진다.
shape 메소드를 통해 배열의 차원과 요소 수가 얼마인지 확인할 수 있다.

## 행렬

In [11]:
n2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

print(n2)
print(n2.shape)
print(len(n2))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
4


## numpy array 초기설정 방법들

1. zeros

In [13]:
n3 = np.zeros(5)
print(n3)
print(n3.shape)

[0. 0. 0. 0. 0.]
(5,)


2. ones

In [15]:
n4 = np.ones((2,3))
print(n4)
print(n4.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


3. 정규분포 상에 있는 난수

In [17]:
n5 = np.random.randn(2,3,4)
print(n5)
print(n5.shape)

[[[-2.19638 -0.40214 -0.44188  0.81474]
  [-0.34231  0.24745 -0.08574  0.344  ]
  [ 0.26917 -0.74128  0.34508  0.08028]]

 [[ 0.59336 -0.7801  -0.32417  1.46569]
  [ 0.04253 -0.06063  0.82023  0.36748]
  [ 0.61711 -0.02871 -2.31857 -1.51581]]]
(2, 3, 4)


In [18]:
n6 = np.linspace(-1,1,11)
print(n6)

[-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]


In [23]:
n7 = np.arange(-1,1.2,0.2)
print(n7)

[-1.  -0.8 -0.6 -0.4 -0.2 -0.   0.2  0.4  0.6  0.8  1. ]
