In [1]:
import numpy as np

# 소수점 5자리까지 표현
np.set_printoptions(suppress=True, precision=5)

In [2]:
# 1차원 배열

n1 = np.array([1, 2, 3, 4, 5])
print('n1.shape: ', n1.shape)

# 2차원 배열 (행렬)

n2 = np.array([
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
    ])

print('n2.shape: ', n2.shape)


n1.shape:  (5,)
n2.shape:  (4, 3)


값을 일일이 지정하지 않고 벡터나 행렬을 정의하는 법: `zeros`, `ones`, `randn` 등의 메서드 이용

In [3]:
n3 = np.zeros(5)
print('n3: ', n3)
print('n3.shape: ', n3.shape)

n3:  [0. 0. 0. 0. 0.]
n3.shape:  (5,)


In [4]:
n4 = np.ones((2,3))
print('n4: ', n4)
print('n4.shape: ', n4.shape)

n4:  [[1. 1. 1.]
 [1. 1. 1.]]
n4.shape:  (2, 3)


In [5]:
# 평균 1, 표준편차 0인 정규분포 데이터 생성

n5 = np.random.randn(2,3,4)
print('n5: ', n5)
print('n5.shape: ', n5.shape)


n5:  [[[ 0.1714   1.76377  0.35521 -0.64006]
  [ 0.09212 -0.02098 -0.04905  0.88438]
  [-0.23138 -1.78002  0.40919  0.12876]]

 [[-0.51669  1.4187   1.23351 -0.25173]
  [ 1.54837  0.907   -0.73951  0.71989]
  [ 1.35818  1.69925 -0.52138 -0.52209]]]
n5.shape:  (2, 3, 4)


### linspace

linspace의 인자: 시작값, 종료값, 간격 지정을 위한 점의 개수

주의: **n 등분을 내고 싶다면 종료값을 n+1로 지정해야 함**

In [6]:
n6 = np.linspace(0, 10, 51)
print('n6: ', n6)
print('n6.shape: ', n6.shape)



n6:  [ 0.   0.2  0.4  0.6  0.8  1.   1.2  1.4  1.6  1.8  2.   2.2  2.4  2.6
  2.8  3.   3.2  3.4  3.6  3.8  4.   4.2  4.4  4.6  4.8  5.   5.2  5.4
  5.6  5.8  6.   6.2  6.4  6.6  6.8  7.   7.2  7.4  7.6  7.8  8.   8.2
  8.4  8.6  8.8  9.   9.2  9.4  9.6  9.8 10. ]
n6.shape:  (51,)


### arange

arange의 인자: 시작값, 종료값, 간격

주의: **두번째 인자인 종료값은 포함되지 않음(종료값 미만)**

In [7]:
n7 = np.arange(0, 11, 1)
print('n7: ', n7) # 11은 포함되지 않음
print('n7.shape: ', n7.shape)

n7:  [ 0  1  2  3  4  5  6  7  8  9 10]
n7.shape:  (11,)


### 특정 행 / 특정 열 추출

In [8]:
n8 = n2[:,0] # 모든 행의 0번째 열 추출

print(n8)

[ 1  4  7 10]


In [9]:
n2_index = np.array([False, True, False, True])
n9 = n2[n2_index]
print(n9)

[[ 4  5  6]
 [10 11 12]]


### reshape

In [10]:
n10 = np.array(range(24))
print(n10)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [11]:
n11 = n10.reshape(2,-1,2)
print(n11)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]
  [18 19]
  [20 21]
  [22 23]]]


In [12]:
print(n10.shape)

n12 = n10.reshape(1,-1)
print(n12.shape)

(24,)
(1, 24)


### 축 교체

In [13]:
n14 = n2.T # 전치 행렬
print(n2.shape)
print(n14.shape)

(4, 3)
(3, 4)


In [14]:
n15 = np.zeros((2,3,4))
print(n15.shape)
n16 = np.transpose(n15, (1,2,0))
print(n16.shape)

(2, 3, 4)
(3, 4, 2)


### 행렬 연결

In [18]:
n17 = np.array(range(1,9)).reshape(2,4)
n18 = np.array(range(9,17)).reshape(2,4)

n19 = np.array(range(1,5))

print(n19.shape)
n20 = np.vstack([n17, n19])

print(n20.shape)

(4,)
(3, 4)


### NumPy의 차원 자동 확장(Broadcasting) 규칙

#### 1차원/2차원 배열의 자동 확장
NumPy는 1차원 배열을 2차원 배열과 함께 사용할 때 자동으로 차원을 확장해주는 기능을 제공함.

#### 예시
```python
import numpy as np

# 2차원 행렬
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])  # shape: (2,3)

# 1차원 벡터
vector = np.array([7, 8, 9])    # shape: (3,)

# 자동 확장되어 vstack 가능
result = np.vstack([matrix, vector])
print(result.shape)  # (3, 3)
```

<br>

### 3차원 이상 배열에서의 제한

3차원 이상의 배열에서는 자동 확장이 지원되지 않는다.

```python
# 3차원 배열과 1차원 배열은 자동 확장 불가
array_3d = np.zeros((1,1,4))
vector = np.array([1,2,3,4])

# 오류 발생
# np.vstack([array_3d, vector])  # ValueError
```